export const JobInfo = [
  {
    jobId: 1,
    jobName: "Call Centre Executive (Night Shift)",
    category: "Customer Support/Call Centre",
    vacancy: 40,
    jobContext: [
      "We are looking for experienced Telemarketers for our USA & Canadian Project",
      "International Telemarketing in USA & Canadian Time (Night Shift Only) & English only.",
      "Office time 9 PM to 6 AM (hours can be 1 hour forward or backward depending on projects.)",
      "Weekly holiday Saturday ,Sunday",
    ],
    jobResponsibilities: [
      "You have to talk through out the full shift in English, Don't bother if you are not a good English Speaker",
      "We are looking for self-driven, self-motivated & dedicated People.",
      "It's a night shift job, So, don't apply if you are not a night hawk",
      "If you don't want to show up for interview, don't apply.",
      "Last but not least No late & absents are allowed",
    ],
    jobType: "Full Time",
    education: [
      "Bachelor of Business Administration (BBA) in Marketing",
      "A - Level/ NSU, IUB, BRAC, AIUB, EAST WEST Graduate/ IELTS Band Score 6",
      "Preferences will be given to people who have returned from Foreign Lands where English is the First Language.",
      "Your Educational background really doesn't matter as long as you are a good English speaker and listener.",
      "Training/ Trade Course: IELTS,English Speaking",
      "Skills Required: Computer skill",
    ],
    experience: ["At least 1 year(s)", "Freshers are also encouraged to apply"],
    additionalRequirement: [
      "Age 18 to 30 years",
      "Both males and females are allowed to apply.",
      "Fluent in English Communication both in Written and Spoken",
      "A candidate who knows the Australian accent will get priority.",
    ],
    workPlace: "Work At Office",
    location: "Uttara(west), Dhaka",
    salary: ["Tk. 15000", "Increment after 3 months."],
    other: ["Salary Review: Half Yearly"],
    howTo:
      "Please email your resume to career@mitaliint.com and Only mention “Call center Executive” as the subject line.",
  },
  {
    jobId: 2,
    jobName: "Call Centre Executive for Australian Solar Campaign (Day Shift)",
    category: "Customer Support/Call Centre",
    vacancy: 10,
    jobContext: [
      "We are looking for experienced Telemarketers for our Australian Project",
      "International Telemarketing in Australia Time & English only.",
      "Office time 6 AM to 3 PM (hours can be 1 hour forward or backward depending on projects.)",
      "Weekly holiday Sunday.",
    ],
    jobResponsibilities: [
      "We are looking for self-driven, self-motivated & dedicated People.",
      "You have to talk throughout the entire shift in English, Don't bother if you are not good at English.",
      "Handle outbound calls to potential customers and sell our products/services",
      "Achieve daily, weekly, and monthly sales target",
      "Provide excellent customer service and build a positive rapport with customers",
      "Record customer information and sales data accurately",
      "Work in a team-oriented environment",
      "Last but not least No late & absents are allowed.",
    ],
    jobType: "Full Time",
    education: [
      "Bachelor of Business Administration (BBA) in Marketing",
      "A - Level/ NSU, IUB, BRAC, AIUB, EAST WEST Graduate/ IELTS Band Score 6",
      "Preferences will be given to people who have returned from Foreign Lands where English is the First Language.",
      "Your Educational background really doesn't matter as long as you are a good English speaker and listener.",
      "Training/ Trade Course: IELTS,English Speaking",
      "Skills Required: Computer skill",
    ],
    additionalRequirement: [
      "Age 18 to 30 years",
      "Both males and females are allowed to apply.",
      "Fluent in English Communication both in Written and Spoken",
    ],
    workPlace: "Work At Office",
    location: "Uttara(west), Dhaka",
    salary: [
      "Tk. 15000 - 20000 (Monthly)",
      "You can earn Up to 5000- 10000 BDT on top of you salary as sales bonus.",
    ],
    other: [
      "Performance bonus, Weekly 2 holidays, Over time allowance, Tour allowance",
      "Salary Review: Yearly",
      "Attendance bonus",
      "Transportation allowance",
      "Yearly tour in Cox's Bazar",
    ],
    howTo:
      "Please email your resume to career@mitaliint.com and Only mention “Call center Executive” as the subject line.",
  },
];
